apiVersion: v1
kind: ConfigMap
metadata:
  name: product-vault-spring-config
data:
  DB_URL: "jdbc:postgresql://postgresql.database.svc.cluster.local:5432/postgres"
  VAULT_SECRET_NAME: "product-vault-spring"
  VAULT_ENABLED: "true"
  VAULT_HOST: "vault.vault.svc.cluster.local"
  VAULT_PORT: "8200"
  VAULT_SCHEME: "http"